// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSIbyjknG-lruc1KWWJzNnLFnCuwBFvh8',
    appId: '1:1016309674553:web:d65d3bedf0dde3559e13e8',
    messagingSenderId: '1016309674553',
    projectId: 'bionic-3',
    authDomain: 'bionic-3.firebaseapp.com',
    storageBucket: 'bionic-3.appspot.com',
    measurementId: 'G-G1F8MME6M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Oqq_aquFN0tCSHyJqIxu10kDKywXkpI',
    appId: '1:1016309674553:android:6891491b3f3821629e13e8',
    messagingSenderId: '1016309674553',
    projectId: 'bionic-3',
    storageBucket: 'bionic-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD112D9ejYIvr8TRODViLug3DoS-iwDKbw',
    appId: '1:1016309674553:ios:2fea78e8fa72e4a39e13e8',
    messagingSenderId: '1016309674553',
    projectId: 'bionic-3',
    storageBucket: 'bionic-3.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD112D9ejYIvr8TRODViLug3DoS-iwDKbw',
    appId: '1:1016309674553:ios:2fea78e8fa72e4a39e13e8',
    messagingSenderId: '1016309674553',
    projectId: 'bionic-3',
    storageBucket: 'bionic-3.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );
}
