// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwvqj2f9-qsBfQugOyFE7lpbpRWTTGRU',
    appId: '1:683720118931:web:adeff60e2166d8e83e3366',
    messagingSenderId: '683720118931',
    projectId: 'bionic-81f51',
    authDomain: 'bionic-81f51.firebaseapp.com',
    databaseURL: 'https://bionic-81f51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bionic-81f51.appspot.com',
    measurementId: 'G-PQSEDES133',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTbC-zaFROjgefH_Na91fuVvAwaOgh8ew',
    appId: '1:683720118931:android:3567fdbe27e410f73e3366',
    messagingSenderId: '683720118931',
    projectId: 'bionic-81f51',
    databaseURL: 'https://bionic-81f51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bionic-81f51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-APb-oQNbismS6iOkdOP-m3nTG466ag',
    appId: '1:683720118931:ios:3e43e742c7800ab43e3366',
    messagingSenderId: '683720118931',
    projectId: 'bionic-81f51',
    databaseURL: 'https://bionic-81f51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bionic-81f51.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-APb-oQNbismS6iOkdOP-m3nTG466ag',
    appId: '1:683720118931:ios:3e43e742c7800ab43e3366',
    messagingSenderId: '683720118931',
    projectId: 'bionic-81f51',
    databaseURL: 'https://bionic-81f51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bionic-81f51.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );
}
