// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK51BIU_raJ649sKatwj-Y_uW4Ff_MzSs',
    appId: '1:467996889533:web:87eae2ea10a5de732ac2d4',
    messagingSenderId: '467996889533',
    projectId: 'bionictest-61a21',
    authDomain: 'bionictest-61a21.firebaseapp.com',
    storageBucket: 'bionictest-61a21.appspot.com',
    measurementId: 'G-4526BMG072',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADz6axVOcne4eusi-SEbMQNY0ZbQdkMHg',
    appId: '1:467996889533:android:efd2d849003c85b22ac2d4',
    messagingSenderId: '467996889533',
    projectId: 'bionictest-61a21',
    storageBucket: 'bionictest-61a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0VXiZ50shg08UqC-CJgULHUrIcAZaNs',
    appId: '1:467996889533:ios:611b930ab0ca4f7f2ac2d4',
    messagingSenderId: '467996889533',
    projectId: 'bionictest-61a21',
    storageBucket: 'bionictest-61a21.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0VXiZ50shg08UqC-CJgULHUrIcAZaNs',
    appId: '1:467996889533:ios:611b930ab0ca4f7f2ac2d4',
    messagingSenderId: '467996889533',
    projectId: 'bionictest-61a21',
    storageBucket: 'bionictest-61a21.appspot.com',
    iosBundleId: 'com.example.flutterTestMuhammadRiski',
  );
}
